name: PR-Alert-Test
on:
  [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Send chat message
      run: curl -X POST -H 'Content-Type: application/json' 
